# action名称
name: Push Release

# 当代码提交到main分支时，执行脚本
on:
  push: branches:[main]

#任务
jobs:
  publish-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
      steps:
        # 检查并切换到主分支
        - name: 检查分支
          uses: actions/checkout@main

        #安装node
        - name: 设置NodeJS
          uses: actions/setup-node@main
          with:
            node-version: ${{ matrix.node-version }}

        # npm install
      - name: npm install and build
        run: |
          cd source
          npm install
          npm run build
          cd ..
          zip –q –r scott-theme.zip /web
        env:
          CI: true
          # 创建GitHub Release
      - name: 创建GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
        	# 配置github token （这个无需去github配置，默认存在的）
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        	# 标签名
          tag_name: v${{steps.version.outputs.value}}
          # release名
          release_name: v${{steps.version.outputs.value}}
          # 是否为草稿
          draft: false
          # 是否为预发布
          prerelease: false
          # 上传Release Asset
      - name: 上传Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        	# 上传URL为创建GitHub Release步骤的输出值，可通过配置的id获取
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # 上传文件信息
          asset_path: ./scott-theme.zip
          asset_name: scott-theme.zip
          asset_content_type: application/zip


