# action名称
name: Push Release

# 当代码提交到main分支时，执行脚本
on:
  push:
    branches:
      - main
#任务
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      # 检查并切换到主分支
      - name: 检查分支
        uses: actions/checkout@main

      #安装node
      - name: 设置NodeJS
        uses: actions/setup-node@main
        with:
          node-version: 16

      # npm install
      - name: npm install and build
        run: |
          cd source
          npm install
          npm run build
          cd ..
          pwd
          tar -zcvf scott-theme.tar.gz --exclude=./source --exclude=./.git --exclude=./.github --exclude=./.gitignore --exclude=./readme.md ./*
      - name: 读取当前版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./source/package.json
          property: version
      - name: 创建GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{steps.version.outputs.value}}
          release_name: v${{steps.version.outputs.value}}
          draft: false
          prerelease: false
      - name: 上传Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./scott-theme.tar.gz
          asset_name: scott-theme.tar.gz
          asset_content_type: application/tar+gzip
